import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles({
  NavRoot: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "10px 0px",
    borderBottom: "0px solid #343f56",
  },
  TabsHead: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
    padding: "10px 0px",
    borderBottom: "0px solid #343f56",
    position: "sticky",
    top: "0",
    backgroundColor: "#f5e6ca",
  },
  TabsBtn1: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "10px 30px",
    margin: "5px 10px",
    fontSize: 17,
    textTransform: "uppercase",
    color: "#343f56",
    backgroundColor: "#f5e6ca",
    border: "none",
    borderRadius: "7px",
    boxShadow: "0px 2px 10px #d2939c",
  },
  TabsBtn2: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "10px 30px",
    margin: "5px 10px",
    fontSize: 17,
    textTransform: "uppercase",
    color: "#f5e6ca",
    backgroundColor: "#343f56",
    border: "none",
    borderRadius: "7px",
    boxShadow: "0px 2px 10px #d2939c",
  },
});
